apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
spec:
  # we have 1 container per pod here - hence array of 1
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        # default port that postgres exposes
        - containerPort: 5432