apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  # we have 1 container per pod here - hence array of 1
  containers:
    - name: result-app
      # https://hub.docker.com/r/dockersamples/examplevotingapp_result
      image: dockersamples/examplevotingapp_result
      ports:
        # exposes port 80 since its a webapp
        - containerPort: 80
