# exposes redis service to other pods/services
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  # This is not an internal service - default is clusterIp.
  # They are internal to cluster.
  # LoadBalancer changes it to be accessible outside cluster.
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    # copied form voting-pod
    # links service to voting pod
    name: voting-app-pod
    app: demo-voting-app